import { chromium } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
const base = process.env.SITE_URL || 'http://127.0.0.1:4173';
const browser = await chromium.launch({ ...(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {}) });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, permissions: ['clipboard-read', 'clipboard-write'], reducedMotion: 'reduce' });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('response', response => { if (response.url().startsWith(base) && response.status() >= 400) errors.push(`${response.status()} ${response.url()}`); });
try {
  await page.goto(base, { waitUntil: 'networkidle' });
  await page.screenshot({ path: '/tmp/ertho-desktop.png', fullPage: true });
  assert.equal(await page.locator('h1').count(), 1);
  const badImages = await page.locator('img').evaluateAll(images => images.filter(img => !img.complete || !img.naturalWidth).map(img => img.src));
  assert.deepEqual(badImages, [], 'All images must load');
  const anchors = await page.locator('a[href^="#"]').evaluateAll(links => links.filter(link => !document.getElementById(link.hash.slice(1))).map(link => link.hash));
  assert.deepEqual(anchors, [], 'All section links must resolve');
  await page.locator('#support details').first().locator('summary').click();
  assert.equal(await page.locator('#support details').first().getAttribute('open'), '');
  await page.locator('#work details').last().locator('summary').click();
  assert.match(await page.locator('#work details').last().innerText(), /adopted constitution/);
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('link', { name: /Conservancy organogram/ }).click();
  assert.equal((await downloadEvent).suggestedFilename(), 'ERTHO-Conservancy-Organogram.png');
  await page.getByRole('button', { name: 'Copy email address' }).click();
  await page.getByRole('status').filter({ hasText: 'Email address copied.' }).waitFor();
  assert.equal(await page.evaluate(() => navigator.clipboard.readText()), 'ertho.environmental@outlook.com');
  const desktopAudit = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
  assert.deepEqual(desktopAudit.violations.map(v => ({ id: v.id, nodes: v.nodes.map(n => n.target) })), [], 'Desktop accessibility');
  for (const width of [320, 390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `No horizontal overflow at ${width}px`);
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(base, { waitUntil: 'networkidle' });
  await page.screenshot({ path: '/tmp/ertho-mobile.png', fullPage: true });
  const toggle = page.getByRole('button', { name: /Menu/ });
  await toggle.click();
  assert.equal(await page.locator('#menu-toggle').getAttribute('aria-expanded'), 'true');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#menu-toggle').getAttribute('aria-expanded'), 'false');
  assert.equal(await page.evaluate(() => document.activeElement.id), 'menu-toggle');
  await toggle.click();
  await page.getByRole('navigation', { name: 'Mobile navigation' }).getByRole('link', { name: 'Our work' }).click();
  assert.equal(await page.locator('#menu-toggle').getAttribute('aria-expanded'), 'false');
  assert.ok(page.url().endsWith('#work'));
  await page.reload({ waitUntil: 'networkidle' });
  assert.ok(page.url().endsWith('#work'));
  const mobileAudit = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
  assert.deepEqual(mobileAudit.violations.map(v => ({ id: v.id, nodes: v.nodes.map(n => n.target) })), [], 'Mobile accessibility');
  const noJsContext = await browser.newContext({ javaScriptEnabled: false, viewport: { width: 390, height: 844 } });
  const noJs = await noJsContext.newPage();
  await noJs.goto(base);
  assert.ok(await noJs.getByRole('navigation', { name: 'Mobile navigation' }).isVisible());
  assert.ok(await noJs.getByRole('link', { name: 'Discuss your initiative' }).first().isVisible());
  await noJsContext.close();
  assert.deepEqual(errors, [], 'No browser or local resource errors');
  console.log('PASS: responsive layouts (320–1440px), images, anchor targets, disclosures, download, clipboard, mobile navigation, deep-link reload, no-JS fallback, desktop/mobile WCAG AA automated checks.');
} finally { await browser.close(); }
